# Ubuntu 14.04 Trusty support
sudo: false
language: cpp
dist: trusty

addons:
  apt:
    packages:
    - cmake

#before_install:
#- git submodule update --init --recursive
before_install:
- sudo apt-get update -qq


script:
- mkdir build
- cd build
- cmake .. && make
- ./bin/peng_motif -h


matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - mpi-default-dev
      env: CXX=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - mpi-default-dev
      env: CXX=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - mpi-default-dev
      env: CXX=g++-6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - mpi-default-dev
      env: CXX=g++-7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - util-linux
            - libc++-dev
            - clang-4.0
            - mpi-default-dev
      env: CXX=clang++-4.0 CXX_FLAGS="-stdlib=libc++" CLANG_VERSION=4.0 CPP=14 ASAN=Off LIBCXX=Off
