# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - cmake

#before_install:
#- git submodule update --init --recursive

script:
- mkdir build
- cd build
- cmake .. && make
- ./bin/peng_motif -h


matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CXX=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CXX=g++-6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: CXX=g++-7

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
            - util-linux
            - libc++-dev
      env: CXX=clang++-3.6 CXXFLAGS="-stdlib=libc++"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - util-linux
            - libc++-dev
      env: CXX=clang++-3.7 CXXFLAGS="-stdlib=libc++"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
            - util-linux
            - libc++-dev
      env: CXX=clang++-3.8 CXXFLAGS="-stdlib=libc++"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - util-linux
            - libc++-dev
      env: CXX=clang++-3.9 CXXFLAGS="-stdlib=libc++"

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - util-linux
            - clang-4.0
            - libc++-dev
      env: CXX=clang++-4.0 CXXFLAGS="-stdlib=libc++"
